CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    email text NOT NULL CHECK (email <> ''),
    password text NOT NULL CHECK (password <> ''),
    phone text NOT NULL CHECK (phone <> ''),
    profile_pic text
);